# Використовуємо базовий образ Python
FROM python:3.13

# Встановлюємо робочу директорію
WORKDIR /app

# Копіюємо файли у контейнер
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копіюємо весь проєкт
COPY . .

# Відкриваємо порт
EXPOSE 5000

# Запускаємо застосунок
CMD ["python", "app.py"]